import { Inter, Plus_Jakarta_Sans, Instrument_Serif } from 'next/font/google'
import AuthGuard from '@/components/AuthGuard'
import PwaProvider from '@/components/PwaProvider'

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '700', '800'], variable: '--font-inter', display: 'swap' })
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'], weight: ['600', '700', '800'], variable: '--font-jakarta', display: 'swap' })
const serif = Instrument_Serif({ subsets: ['latin'], weight: '400', style: 'italic', variable: '--font-serif', display: 'swap' })

const SITE = 'https://www.hayyaai.com'
const DESC = 'Hayya AI is an AI customer-engagement platform: WhatsApp & Instagram AI agents, an omnichannel inbox, CRM, and automation. Built & operated by Hayya Med AI in Doha, Qatar.'

export const metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: 'Hayya AI — AI Agents for WhatsApp, Instagram & CRM',
    template: '%s · Hayya AI',
  },
  description: DESC,
  keywords: [
    'AI agent', 'WhatsApp AI', 'Instagram DM automation', 'AI chatbot Qatar',
    'omnichannel inbox', 'CRM Qatar', 'customer engagement AI', 'GCC AI platform',
    'WhatsApp Business API', 'AI customer support', 'Hayya AI', 'Hayya Med AI',
  ],
  authors: [{ name: 'Hayya Med AI', url: 'https://hayyamed.ai' }],
  creator: 'Hayya Med AI',
  publisher: 'Hayya Med AI',
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE,
    siteName: 'Hayya AI',
    title: 'Hayya AI — AI Agents for WhatsApp, Instagram & CRM',
    description: DESC,
    // Social card generated by app/opengraph-image.js (branded 1200×630 PNG).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Hayya AI — AI Agents for WhatsApp, Instagram & CRM',
    description: DESC,
  },
  robots: {
    index: true, follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
  appleWebApp: { capable: true, statusBarStyle: 'black-translucent', title: 'Hayya AI' },
  icons: { icon: '/logo.svg', apple: '/logo.svg' },
}

// Structured data (JSON-LD) for rich search results.
const JSONLD = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${SITE}/#org`,
      name: 'Hayya AI',
      url: SITE,
      logo: `${SITE}/logo.svg`,
      parentOrganization: { '@type': 'Organization', name: 'Hayya Med AI', url: 'https://hayyamed.ai' },
      founder: { '@type': 'Person', name: 'Abbas Al Masri' },
      foundingDate: '2025',
      email: 'abbas@hayyamed.ai',
      telephone: '+974 3367 7333',
      address: { '@type': 'PostalAddress', addressLocality: 'Doha', addressCountry: 'QA' },
      areaServed: ['QA', 'GCC', 'MENA'],
    },
    {
      '@type': 'WebSite',
      '@id': `${SITE}/#website`,
      url: SITE,
      name: 'Hayya AI',
      publisher: { '@id': `${SITE}/#org` },
      inLanguage: 'en',
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Hayya AI',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web, iOS, Android',
      description: DESC,
      offers: { '@type': 'Offer', price: '150', priceCurrency: 'QAR' },
      aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', ratingCount: '37' },
    },
  ],
}

export const viewport = {
  themeColor: '#070b0a',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  viewportFit: 'cover',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${jakarta.variable} ${serif.variable}`}>
      <head>
        {/* Warm up the connections used by the hero video + API (LCP/CWV) */}
        <link rel="preconnect" href="https://stream.mux.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://stream.mux.com" />
        <link rel="preconnect" href="https://api.hayyaai.com" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(JSONLD) }} />
        <style dangerouslySetInnerHTML={{ __html: `
          @keyframes hai-float   { 0%,100%{transform:translate3d(0,0,0)} 50%{transform:translate3d(0,-22px,0)} }
          @keyframes hai-float2  { 0%,100%{transform:translate3d(0,0,0)} 50%{transform:translate3d(0,26px,0)} }
          @keyframes hai-drift   { 0%{transform:translate3d(0,0,0) scale(1)} 50%{transform:translate3d(30px,-20px,0) scale(1.08)} 100%{transform:translate3d(0,0,0) scale(1)} }
          @keyframes hai-spin    { to{transform:rotate(360deg)} }
          @keyframes hai-shimmer { 0%{background-position:-200% 0} 100%{background-position:200% 0} }
          @keyframes hai-pulse   { 0%,100%{opacity:.5} 50%{opacity:1} }
          @keyframes hai-grid    { 0%{background-position:0 0} 100%{background-position:48px 48px} }
          .hai-reveal { opacity:0; transform:translate3d(0,28px,0); transition:opacity .7s cubic-bezier(.2,.7,.2,1), transform .7s cubic-bezier(.2,.7,.2,1); will-change:opacity,transform; }
          .hai-reveal.in { opacity:1; transform:translate3d(0,0,0); }
          .hai-orb { position:absolute; border-radius:50%; filter:blur(60px); pointer-events:none; }
          .hai-shimmer { background:linear-gradient(100deg,#EAD9A6 20%,#D8B16A 45%,#fff7e6 50%,#D8B16A 55%,#A07C3A 80%); background-size:200% auto; -webkit-background-clip:text; background-clip:text; -webkit-text-fill-color:transparent; animation:hai-shimmer 6s linear infinite; }
          @media (prefers-reduced-motion: reduce) {
            .hai-reveal{opacity:1!important;transform:none!important;transition:none!important}
            .hai-orb,.hai-shimmer,[data-anim]{animation:none!important}
          }
        ` }} />
      </head>
      <body>
        <AuthGuard>{children}</AuthGuard>
        <PwaProvider />
      </body>
    </html>
  )
}
