export const FEATURES_CONTENT = [
  {
    slug: 'omnichannel-inbox',
    icon: '💬',
    title: 'Omnichannel Inbox',
    color: '#D8B16A',
    tagline: 'WhatsApp, Instagram, Facebook, Telegram, and Email — one inbox, zero missed messages.',
    metaTitle: 'Omnichannel Inbox — WhatsApp, Instagram & Email CRM | Hayya AI',
    metaDescription: 'Manage WhatsApp, Instagram, Facebook, Telegram, and Email from one unified inbox. Hayya AI\'s omnichannel CRM built for Qatar and GCC businesses.',
    intro: 'Customers reach out on whatever channel is convenient for them — a WhatsApp message, an Instagram DM, a Facebook comment, an email. Without a unified inbox, that means checking five different apps and inevitably missing something. Hayya AI brings every conversation into one place, so your team never has to context-switch between apps to respond.',
    capabilities: [
      { title: 'Real Channel Coverage', desc: 'WhatsApp Business API, Instagram DMs, Facebook Messenger, Telegram, and Email — all genuinely connected, not a partial integration.' },
      { title: 'Unified Conversation View', desc: 'Every customer\'s full conversation history in one thread, regardless of which channel they used to reach out.' },
      { title: 'Team Assignment & Routing', desc: 'Route conversations to the right team member automatically, with visibility into who\'s handling what.' },
      { title: 'Fast, Mobile-Ready Interface', desc: 'A genuinely fast inbox interface that works well on mobile, since customer conversations don\'t wait for you to be at a desk.' },
    ],
  },
  {
    slug: 'ai-auto-reply',
    icon: '🤖',
    title: 'AI Auto-Reply',
    color: '#a78bfa',
    tagline: 'AI agents that respond instantly in Arabic and English — qualifying leads and booking appointments 24/7.',
    metaTitle: 'AI Auto-Reply for WhatsApp & Instagram (Arabic & English) | Hayya AI',
    metaDescription: 'AI agents that respond instantly to customer messages in Arabic and English — qualifying leads, answering questions, and booking appointments around the clock.',
    intro: 'The gap between a customer message and your team\'s response is where deals are lost — a lead that messages at 11pm and doesn\'t hear back until the next morning has often already moved on. Hayya AI\'s AI agents respond immediately, in the customer\'s own language, and hand off to a human exactly when human judgment is actually needed.',
    capabilities: [
      { title: 'Bilingual by Design', desc: 'Genuinely fluent Arabic and English responses, not a translated afterthought — critical for a real GCC customer base.' },
      { title: 'Lead Qualification', desc: 'The AI asks the right qualifying questions automatically, so your team only spends time on leads worth pursuing.' },
      { title: 'Instant Booking', desc: 'Customers can book an appointment directly through the conversation, no back-and-forth required.' },
      { title: 'Clean Human Handoff', desc: 'When a conversation needs a human touch, the AI hands off cleanly with full context — no repeating themselves for the customer.' },
    ],
  },
  {
    slug: 'crm-lead-scoring',
    icon: '📊',
    title: 'CRM & Lead Scoring',
    color: '#3b82f6',
    tagline: 'AI scores every lead 0–100 — full visibility into contacts, conversations, and deal stages.',
    metaTitle: 'AI Lead Scoring CRM for WhatsApp & Instagram Leads | Hayya AI',
    metaDescription: 'AI-powered lead scoring (0-100) and full CRM visibility into contacts, conversations, and deal stages — built for WhatsApp and Instagram-driven sales teams.',
    intro: 'Not every conversation is a real sales opportunity, and figuring out which ones are worth prioritizing shouldn\'t require a sales manager manually reviewing every chat. Hayya AI\'s AI scores every lead based on real signals from the conversation itself, so your team knows exactly where to focus.',
    capabilities: [
      { title: 'Automated Lead Scoring', desc: 'Every lead scored 0-100 based on real conversation signals — intent, urgency, budget cues — not a static form field.' },
      { title: 'Full Contact History', desc: 'Every interaction, across every channel, attached to one contact record.' },
      { title: 'Visual Deal Pipeline', desc: 'Track deals through your actual sales stages with full team visibility.' },
      { title: 'Exportable, Ownable Data', desc: 'Your customer data stays yours — exportable, not locked into a proprietary format.' },
    ],
  },
  {
    slug: 'bulk-campaigns',
    icon: '📣',
    title: 'Bulk Campaigns',
    color: '#f97316',
    tagline: 'Send WhatsApp and email campaigns to thousands — AI generates the copy, you set the audience.',
    metaTitle: 'WhatsApp & Email Bulk Campaigns with AI Copy | Hayya AI',
    metaDescription: 'Send WhatsApp and email marketing campaigns to thousands of contacts. AI generates the campaign copy — you just set the audience and send.',
    intro: 'Reaching your full contact list with a promotion, an announcement, or a seasonal greeting shouldn\'t require a marketing team and a week of drafting. Hayya AI lets you define an audience segment and generates the campaign copy for you — genuinely on-brand, not generic template language.',
    capabilities: [
      { title: 'WhatsApp & Email Campaigns', desc: 'Bulk-send through both channels, respecting each platform\'s real delivery and opt-out rules.' },
      { title: 'AI-Generated Copy', desc: 'Campaign copy drafted by AI based on your goal and audience — you review and send, not write from scratch.' },
      { title: 'Audience Segmentation', desc: 'Target campaigns to specific contact segments based on lead score, tags, or conversation history.' },
      { title: 'Delivery & Response Tracking', desc: 'Real visibility into delivery rates and response engagement, not a black-box send.' },
    ],
  },
  {
    slug: 'automation-builder',
    icon: '⚡',
    title: 'Automation Builder',
    color: '#fbbf24',
    tagline: 'Visual workflow automation — Trigger → Condition → AI Reply → Tag → Book — without code.',
    metaTitle: 'No-Code Automation Builder for Customer Workflows | Hayya AI',
    metaDescription: 'Build visual, no-code automation workflows: trigger, condition, AI reply, tag, and booking steps — automate customer engagement without hiring a developer.',
    intro: 'Every business has repetitive customer-engagement workflows — a specific follow-up sequence, a tagging rule, an automatic booking confirmation — that shouldn\'t require a developer to set up. Hayya AI\'s automation builder is genuinely visual and no-code: define a trigger, a condition, and the actions that follow.',
    capabilities: [
      { title: 'Visual Workflow Design', desc: 'Build automation flows by connecting steps visually — no code, no developer required.' },
      { title: 'Rich Trigger & Condition Logic', desc: 'Trigger workflows off real events (new message, tag applied, time elapsed) with genuine conditional branching.' },
      { title: 'AI-Powered Steps', desc: 'Include AI-generated replies as a step within a broader automated workflow, not just as a standalone chatbot.' },
      { title: 'Tagging & Booking Actions', desc: 'Automatically tag contacts and trigger bookings as part of the same automated flow.' },
    ],
  },
  {
    slug: 'booking-system',
    icon: '📅',
    title: 'Booking System',
    color: '#06b6d4',
    tagline: 'Built-in appointment booking — clients book via chat, you confirm in one click, calendar sync included.',
    metaTitle: 'In-Chat Appointment Booking System | Hayya AI',
    metaDescription: 'Built-in appointment booking directly inside WhatsApp and Instagram conversations, with one-click confirmation and calendar sync.',
    intro: 'Sending a customer to a separate booking website to schedule an appointment is exactly the kind of friction that loses a booking. Hayya AI lets customers book directly inside the conversation they\'re already having with you, with your calendar staying in sync automatically.',
    capabilities: [
      { title: 'In-Chat Booking', desc: 'Customers book an appointment slot directly within WhatsApp or Instagram, no separate website required.' },
      { title: 'One-Click Confirmation', desc: 'Confirm or reschedule a booking in one click from your dashboard.' },
      { title: 'Calendar Sync', desc: 'Bookings sync with your real calendar, avoiding double-booking.' },
      { title: 'Automated Reminders', desc: 'Automatic reminder messages sent ahead of the appointment, reducing no-shows.' },
    ],
  },
]

export function getFeatureContent(slug) {
  return FEATURES_CONTENT.find((f) => f.slug === slug)
}
